### ISSUE TITLE
Use `require` and not fs to load config files

### ISSUE THREAD

**Issue by adiologydev** [countr/countr#1]
As your config file is a JSON, please use the native thing which would be `require` in your case.

You currently require config through the following methods:

    const config = JSON.parse(fs.readFileSync("./config.json"))
    const config = JSON.parse(require("fs").readFileSync("./config.json", "utf8"))

Which is firstly inconsistent in different files and then again, why are you reading them through `fs` in the first place?

The proper way of doing this would be:

    const config = require("./config.json")

and that's it.

**Comment by promise** [comment]
Thank you for letting me know, it will be fixed when language support rolls out.
