### ISSUE TITLE
Add two other lines to the info command to make all fields even with 4 lines each instead of 3,4,3

### ISSUE THREAD

**Issue by promise** [countr/countr#102]
# Feature request

Add two other lines to the info command to make all fields even with 4 lines each instead of 3,4,3. See #101

**Comment by wrac4242** [comment]
host uptime for the hosts
and its 3,3,4 at the moment, so stats needs a field
total count?

**Comment by promise** [comment]
Another solution to this would be just removing the uptime (there's really no need for it, they can just execute the ping command instead)

**Comment by promise** [comment]
Fixed 👍
