### ISSUE TITLE
unpin action in flow

### ISSUE THREAD

**Issue by wrac4242** [countr/countr#105]
# Feature request

an action that allows the unpinning of the last run pin action by the flow itself

The given example is to pin every 100th number number, but only have the newest one pinned

(idea courtesy of 195o#3435 on the discord)

**Comment by wrac4242** [comment]
Could this be implemented by: 

- giving each flow another property, 
    - which is the message ID of the last pinned message of the flow, and 
- on the unpin action it checks whether the last pinned message ID exists, 
    - if so it unpins it, making sure that each flow is independent

**Comment by promise** [comment]
don't see a reason why this would be used and useful. would like more comments on how this would be used on a server.

**Comment by wrac4242** [comment]
I think the person who suggested it wanted to have in the pins only the latest time a flow was triggered, possibly to reduce the amount of pinned messages. But again its not my idea, its 195o#3435 on discord idea

**Comment by promise** [comment]
Not going to implement, not as of right now.
