### ISSUE TITLE
Command permissions

### ISSUE THREAD

**Issue by Astropipe** [countr/countr#112]
# Feature request

Being able to limit commands to roles, channels, etc etc.

We have a 240 000 member server and if you have even have 50 idiots spamming the everyone commands in the counting channel it's gonna either break the bot or simply overflow the channel.

This is needed because the advice of remove the view permissions of the bot in the other channels is not enough as it still triggers all commands in the counting channel.

So good solutions would be (individual or as a whole):
- Make it so that when a counting channel is set up the bot doesn't listen to commands in that channel
- Being able to limit the commands to a specific channel only
- Being able to limit specific commands to a specific role(s) only

Best option would be (certainly for larger servers):
- Create a config (not per se full worked out dashboard, just config file) where the commands have there own permissions so you can set them all manually 'can_info' and such based on permission levels (this would be handy for larger serves like ours as we usually have people that can easily work with those configs) ==> customizability is a major need in big servers ==> idiotproofing

Using a config would also make it easier to set up flows and everything. A config is cleaner overall and gives the a proper view of how the bot it set up instead of loose commands

**Comment by lacuna-exe** [comment]
![54904266-AA34-416A-88FA-F9F71315654E](https://user-images.githubusercontent.com/72464187/118808022-01750f80-b877-11eb-993c-ab27b9be33d0.jpeg)
(From the support discord server)

**Comment by Astropipe** [comment]
That's not at all what I'm saying, more the exact opposite.
I want to restrict commands, not give them free for all.
This is what I mean with server levels 

Like this you can limit commands to a certain level instead of only behind server manage, role manage and such

![image](https://user-images.githubusercontent.com/30569805/118973871-72e5b880-b972-11eb-960b-3091a3d9ea47.png)

**Comment by promise** [comment]
Might make something in the future for this, maybe in the d.js^13 rewrite. But feel free to self-host it until then.

I understand what you mean, it's been requested before as well.

The thing is, this will confuse a lot of new users using the bot. But maybe I can make two systems and the server owner can choose which one they want to opt in to.

**Comment by Astropipe** [comment]
It def would be nice, certainly for large servers like ours. 
Bunch of randoms with spam tendencies with access to commands is not the best thing.

Small servers usually don't have issues with this

**Comment by promise** [comment]
As Discord has introduced and forced slash commands (see https://support-dev.discord.com/hc/en-us/articles/4404772028055), this will be harder to implement. I am patiently waiting for global slash command permissions to come out, and depending on how they are set up, I might be able to implement this.

**Comment by promise** [comment]
Seems like Discord will implement its own permission system (see https://somber-heron-0d1.notion.site/DDevs-Permissions-v2-a2c5724e8531452d81b6359e4402f09b and https://msciotti.notion.site/msciotti/Command-Permissions-V2-4d113cb49090409f998f3bd80a06c3bd - basically the same, just two different notions) so this issue will be fixed in the rewrite. Seems like it will be very easy to implement.

**Comment by Ta1al** [comment]
This is now possible with discord's slash command permissions
https://discord.com/blog/slash-commands-permissions-discord-apps-bots

**Comment by promise** [comment]
Implemented by Discord, as said by Talal 👍
