### ISSUE TITLE
Can't make a message flow send in a news channel

### ISSUE THREAD

**Issue by RuralAnemone** [countr/countr#117]
Technically I can, but it needs to be a normal text channel first.
![image](https://user-images.githubusercontent.com/64103005/120088166-895fe280-c0dd-11eb-90f9-42f7fb76af87.png)
The bot can send messages in news channels, but only after the flow has saved and I change the channel type back to news.

**Comment by RuralAnemone** [comment]
well
uh
alright then
kind of a strange thing to do
but okay

**Comment by djohts** [comment]
huh
