### ISSUE TITLE
Different types of counting channels, essentially

### ISSUE THREAD

**Issue by RuralAnemone** [countr/countr#118]
# Feature request

A suggestion from a friend, it was suggested in our counting server and I thought I'd post it here as a feature request:

> Different types of counting channel that won't count towards the main one, I'll list a few ideas I have for this: Reverse counting: you start at a set number and have to count down to 0 before a time limit expires, if you reach 0 you can do giveaways or something. Solo: Like spam, but anyone can open a Solo channel, set a number they want to get to, then count to it. (dunno how it would work tho)

**Comment by promise** [comment]
I know it's not *exactly* what you requested in your feature request but we will be adding support for multiple counting channels in v13.

Closing as it has low demand right now. Might reopen in a later time.

**Comment by RuralAnemone** [comment]
well it's better than nothing - thanks!
