### ISSUE TITLE
add rolling restart functionality to the bot

### ISSUE THREAD

**Issue by wrac4242** [countr/countr#120]
Add a command that restarts each shard one by one. This can help with rate limiting and downtime on restarts.

**Comment by wrac4242** [comment]
Could we bump this to a current version task? due to the current issues

**Comment by promise** [comment]
current issues are related to certain channel types, this won't affect anything.
i know this is an old issue but it will be fixed in the rewrite.

**Comment by promise** [comment]
just realized that since we will be using clusters, this will not really work. the clusters auto-restarts whenever they fail, and the manager is set up so clusters won't start at the same time but rather wait.

closing
