### ISSUE TITLE
Able to set flow setup channel as message sending channel 

### ISSUE THREAD

**Issue by wrac4242** [countr/countr#125]
# Bug Report

Create a flow, edit action 1, send message action, then send a link to the flow setup channel

## Expected behavior

Does not accept it as a valid channel

## Screenshots

![image](https://user-images.githubusercontent.com/42539664/126814634-64a7e15b-768c-4de0-b41d-68cf4085a1e4.png)

**Comment by djohts** [comment]
found a solution, currently testing it
