### ISSUE TITLE
Add thread support

### ISSUE THREAD

**Issue by wrac4242** [countr/countr#128]
# Feature request
add thread support to the bot, possibly with either auto sending of messages to keep the thread alive, or unarchiving the thread

**Comment by promise** [comment]
..?

**Comment by wrac4242** [comment]
for example replacing this 
![image](https://user-images.githubusercontent.com/42539664/127216555-26af23cb-5dfd-4946-bc89-c11e95d6ef88.png)

**Comment by djohts** [comment]
I don't think there's a reason for doing this

**Comment by promise** [comment]
TBD when djs^13 is out

**Comment by promise** [comment]
yeah, will be supported in v13.

Closing as this will basically be supported by just installing discord.js v13, and therefore not an issue anymore.
