### ISSUE TITLE
bug: running `/flows create` fails in channels where the bot can't read messages

### ISSUE THREAD

**Issue by djohts** [countr/countr#1295]
unironically, the permission check fails because the bot doesn't have the Read Messages permission 🙏

**Comment by promise** [comment]
possible fix would be to add `.catch(() => null)` to the `fetch()`-es here
https://github.com/countr/countr/blob/a09f709b92fe7b90dad2167fbff732e593e18c71/src/constants/editors/flows/index.ts#L15-L16
