### ISSUE TITLE
change off discord erlpack

### ISSUE THREAD

**Issue by wrac4242** [countr/countr#131]
# Bug Report

when trying to npm install on the discord JS 13 branch, an error is formed. this is [noted in the repo and fixed in a PR](https://github.com/discord/erlpack/pull/40), however the repo has not been updated in over a year and has not merged relevant pull requests

This is tested on fedora 34 linux, and seems to be a lack of support for npm 16

## Reproducing

checkout branch djs-13
run `npm install`

## Expected behavior

successful install

**Comment by wrac4242** [comment]
this can either be fixed with that PR being merged, or changing to a different erlpack

**Comment by djohts** [comment]
https://github.com/discord/erlpack just doesn't work on nodejs v16

**Comment by wrac4242** [comment]
npm v16 is required for djs 13 however, so that causes some issues

**Comment by promise** [comment]
not a bug with master/current version of Countr. djs-13 is WIP and bugs are expected.

**Comment by djohts** [comment]
> npm v16 is required for djs 13 however, so that causes some issues

just to clarify, npm is v7, v16 is nodejs' version

**Comment by splatterxl** [comment]
> not a bug with master/current version of Countr. djs-13 is WIP and bugs are expected.

Actually, v13 is a stable release.

**Comment by wrac4242** [comment]
they are referring to the staging and moving over branch

**Comment by promise** [comment]
> > not a bug with master/current version of Countr. djs-13 is WIP and bugs are expected.
> 
> Actually, v13 is a stable release.

wrac is correct, I'm referring to the branch. but discord.js version 13 is still not perfect either
