### ISSUE TITLE
New regex module crashes on some regex filters it thinks are invalid

### ISSUE THREAD

**Issue by promise** [countr/countr#133]
# Bug Report

New regex module crashes on some regex filters it thinks are invalid

## Reproducing

1. Must already have a server with a valid regex including `(?!`
2. Try to count without having manage messages

## Expected behavior

Should work fine as a regex. Doesn't work anymore because of our new regex module.

## Screenshots

![image](https://user-images.githubusercontent.com/10573728/128627920-5732264f-38ee-4887-96e8-c957d599da90.png)

**Comment by wrac4242** [comment]
this seems to be an issue with the type / "flavour" of regexes it expects, as "perl" is a programming language it has its own flavour of regexes. These flavours all have the same standard base, however are expanded in a variety of different non standard ways. This is expressed in a quote from [this wikipedia page](https://en.wikipedia.org/wiki/Regular_expression).
 "Perl-derivative regex implementations are not identical and usually implement a subset of features"

**Comment by promise** [comment]
Fixed 👍
