### ISSUE TITLE
A penalty for those missing the counter

### ISSUE THREAD

**Issue by Lag2501** [countr/countr#141]
# Feature request

Allowing the possibility to add a penalty for those missing the counter. If you miss you can get -10 or -20 on your score and in the leaderboard for example. A way to make to reward people who don't miss and punish those who do. Simple way to create a real stake on the counter.

And in case of errors with the BOT, it could be nice for an admin to be able to give points back of course :)

**Comment by promise** [comment]
This is now possible using a timeout role and a flow 👍
