### ISSUE TITLE
Trigger Req: Score >= X

### ISSUE THREAD

**Issue by QaisZAK** [countr/countr#143]
# Feature request

I think adding a trigger where the user's score is X or more could be superb. I had an event where you had to count at least 150 times to be eligible for a giveaway, I was hoping the bot could see if a user has 150 >= and assign a role accordingly.

I understand they may spam triggers because every count from a user that is already above X could trigger actions but I think you could work around it. I specifically want this for role assignment, nothing else but decipher as you see suitable.

**Comment by promise** [comment]
You only need to give a role once though..?

**Comment by QaisZAK** [comment]
Yes, understandable but I haven't created a workflow from the beginning as it was a bit intimating and after I understood it users have already passed 150 and it's difficult to manually assign them. I do get your point though

**Comment by promise** [comment]
we can definitely do this. Might be more tricky as we're probably going to be rate limited if we try to add the role each time, but that's just something we need to work around with checks.

**Comment by QaisZAK** [comment]
Could check if the user has the role before assigning so you don't get rate limited. DJs cache comes in handy here

**Comment by promise** [comment]
problem is, djs cache isn't reliable at all
