### ISSUE TITLE
funky leaderboard

### ISSUE THREAD

**Issue by RuralAnemone** [countr/countr#146]
# Bug Report

leaderboard displays seemingly random userids instead of the users of the server

## Reproducing

1. Run command `c?^`

## Expected behavior vs. Actual behavior
1 -  showing only the server's leaderboard
2 - no idea whose userids those are
A clear description of what you expected to happen and what actually happened:
I wanted to check my placement on the server leaderboard, so I used the command c?^
It did not work as expectd.
I am evidently 49th place in a server who has like 10 members.

## Screenshots
![Screenshot 2021-12-16 19 16 13](https://user-images.githubusercontent.com/64103005/146472955-10c50794-7c51-4410-9816-ddfc42e7cfdb.png)

**Comment by Milo123459** [comment]
this isn't a bug, this just means the user isn't cached on your discord client.

**Comment by RuralAnemone** [comment]
oh okay
good to know

**Comment by RuralAnemone** [comment]
although
we've only counted to like 250 so far
If I understand what you're saying correctly

the highest count is 1268
which doesn't work...

**Comment by Milo123459** [comment]
i dont know

**Comment by lacuna-exe** [comment]
This would be better suited for the support server ( https://promise.solutions/support )

**Comment by RuralAnemone** [comment]
gotcha

Den tors 16 dec. 2021 kl 22:41 skrev Void ***@***.***>:

**Comment by promise** [comment]
issue moved to support server, closing this
