### ISSUE TITLE
Detect scores off the counting channel

### ISSUE THREAD

**Issue by promise** [countr/countr#16]
(Inspired by #15)

# Feature request

Add a command to detect all the message counts in the counting channel, and then send a JSON-file back (that you then can import in with the [importscores-command](https://countr.xyz/#/commands?id=cimportscores).)

**Comment by promise** [comment]
Just realized this will have some disadvantages, such as those using webhooks or reposting-modules won't have the ability to do this. I can still implement this for those who transfer over from another bot to Countr though, and those who don't use the reposting modules.

**Comment by hemangsrr** [comment]
Just a few thoughts
1. upon execution of the command first check for reposting or webhook status
2. If reposting enabled, instead of counting messages from user, count user mentions
3. If webhook enabled, add count to user with the same username as the webhook post

there is a lot of loopholes in webhook still,

- multiple people with same name
- people changing usernames etc

**Comment by promise** [comment]
I guess this would be more for when switching from a different bot to Countr. There's no need to detect scores off when using reposting/webhook/embed-modules when their scores have already been modified.

**Comment by RuralAnemone** [comment]
> Just realized this will have some disadvantages, such as those using webhooks or reposting-modules won't have the ability to do this. I can still implement this for those who transfer over from another bot to Countr though, and those who don't use the reposting modules.

You might be able to implement the userid in the webhook/repost name title...?
Not sure if that would be detectable though, at least for the webhook...
as well as the fact that you'd need to do an update for the userid thing, and one for the counting detection, and if people have been counting before the hypothetical userid update, it would break (or something).

**Comment by promise** [comment]
> > Just realized this will have some disadvantages, such as those using webhooks or reposting-modules won't have the ability to do this. I can still implement this for those who transfer over from another bot to Countr though, and those who don't use the reposting modules.
> 
> You might be able to implement the userid in the webhook/repost name title...?
> Not sure if that would be detectable though, at least for the webhook...
> as well as the fact that you'd need to do an update for the userid thing, and one for the counting detection, and if people have been counting before the hypothetical userid update, it would break (or something).

If someone has counted with Countr, even if it's reposted via embed or webhook, their score would already have been updated. This feature is more for those transferring from another bot to Countr and need to get all the users' scores from the channel.

**Comment by RuralAnemone** [comment]
oh yeah good point :)
