### ISSUE TITLE
[BOT] Announce when a message is deleted or edited in the counting channel

### ISSUE THREAD

**Issue by Al-Kohollik** [countr/countr#18]
# Feature request

Add a setting that toggles the bot to send a message when a message is deleted by a human user in the counting channel.

For example:
```
User1: 1

User2: 2

*user3 deletes message*

Countr: User3's message was deleted/edited:

         '3'

User4: 4
```

**Comment by fabianneufang** [comment]
This issue is invalid, because we already have a feature to prevent users from deleting their messages.
