### ISSUE TITLE
[DOCS] Typo

### ISSUE THREAD

**Issue by AkaEthan110** [countr/countr#22]
# Typo

In the 'admins' section underneath 'optional', it says "No, but recommended". Basically, it is saying that admins isn't optional but it is recommended. That doesn't make sense. I would recommend changing it to "Yes, but recommended". If you did so, it would be saying that admins is optional but it is recommended.

tl;dr - To be grammatically correct in the 'admins' bit, for 'optional', it should say "Yes, but recommended".

**How to get to the typo:**
Go to the Countr documentation --> How to setup --> Self-hosting --> Configuration --> admins

## Screenshots

[1] https://prnt.sc/ryeedx

**Comment by promise** [comment]
It should've said "Required" instead of "Optional" ... because a Discord token is indeed required for a Discord bot to work... Thanks for bringing it to my attention.

**Comment by AkaEthan110** [comment]
Ah, yes. I didn't notice that.

**Comment by THErealARETE** [comment]
can I open a pull request to this effect, would be very helpful

**Comment by fabianneufang** [comment]
@THErealARETE You dont have to ask for opening a PR.

**Comment by fabianneufang** [comment]
I've made the PR

**Comment by promise** [comment]
N/A, new docs will come with the rewrite
