### ISSUE TITLE
Incorrect fail after someone else fails when restarting count

### ISSUE THREAD

**Issue by MattTheCuber** [countr/countr#220]
# Bug Report

__This applies to when you have reset the count after a fail.__
When someone fails and you were the previous counter, it deletes the failing person's message. Then when you try to count you fail, because the bot is checking the last person to send a count (which is you because the failing person's message was deleted).

## Reproducing

Counting example:
1. MattTheCuber: 50
2. ~~AnotherPerson: 49~~ - gets deleted
3. AnotherPerson failed
4. ~~MattTheCuber: 1~~ - gets deleted
5. MattTheCuber failed - should allow because the count was reset
6. ~~MattTheCuber: 1~~ -  gets deleted
7. MattTheCuber failed
8. AnotherPerson: 1
9. MattTheCuber: 2

## Expected behavior vs. Actual behavior

I would expect that, in this example, MattTheCuber would be able to start the new count since it was reset and the previous counter failed.

## Screenshots

I can get some if you don't understand.

**Comment by promise** [comment]
Can confirm this is an issue. The code only sets the count, it doesn't reset who counted last: https://github.com/countr/countr/blob/djs-12/src/constants/flows/flow.js#L121

Issue is temporarily fixed and will take effect whenever the bot or the shards restart. (so it might not be live for everyone just yet) - But permanent fix is already implemented in the rewrite which is coming within April.

**Comment by MattTheCuber** [comment]
Wow, that was quick and very useful. Thank you so much! (Also, no rush you now have until August 31st! XD

**Comment by promise** [comment]
> Also, no rush you now have until August 31st! XD

yeah, just read the deadline is moved. I will still try to release the rewrite before then though.

**Comment by MattTheCuber** [comment]
This just came back, probably because of the new release

**Comment by MattTheCuber** [comment]
@promise this issue came back upon slash command release

**Comment by djohts** [comment]
> @promise this issue came back upon slash command release

there is no reset count action now though (at least I can't find it, so correct me if i'm wrong)
now there's only set count action

**Comment by MattTheCuber** [comment]
> > @promise this issue came back upon slash command release
> 
> there is no reset count action now though (at least I can't find it, so correct me if i'm wrong) now there's only set count action

![image](https://user-images.githubusercontent.com/32849887/184551577-b8a218de-2413-434f-9d1b-d52f8abdce51.png)

**Comment by djohts** [comment]
> > > @promise this issue came back upon slash command release
> > 
> > 
> > there is no reset count action now though (at least I can't find it, so correct me if i'm wrong) now there's only set count action
> 
> ![image](https://user-images.githubusercontent.com/32849887/184551577-b8a218de-2413-434f-9d1b-d52f8abdce51.png)

as i said, its **set** the count now, not **reset**

**Comment by itzJOHv** [comment]
> > > @promise this issue came back upon slash command release
> > 
> > 
> > there is no reset count action now though (at least I can't find it, so correct me if i'm wrong) now there's only set count action
> 
> ![image](https://user-images.githubusercontent.com/32849887/184551577-b8a218de-2413-434f-9d1b-d52f8abdce51.png)

as i said, its **set** the count now, not **reset**

**Comment by promise** [comment]
* will be fixed
* this is my fifth ping, please stop

**Comment by MattTheCuber** [comment]
> as i said, its **set** the count now, not **reset**

My bad

**Comment by MattTheCuber** [comment]
> * this is my fifth ping, please stop

Sorry! I didn't see any open issues 😬
