### ISSUE TITLE
When talking module is enabled allow people to talk after the number with a space

### ISSUE THREAD

**Issue by MattTheCuber** [countr/countr#229]
# Feature request

Basically just grab every character until you find a non-digit in the first word when looking for the count.

![image](https://user-images.githubusercontent.com/32849887/163390693-f359dfbf-f867-423d-8f61-49ebe433d93e.png)

**Comment by wrac4242** [comment]
I am not entirely sure what you are asking, as the talking module does allow you to add messages after the count, separated by a space. 
![image](https://user-images.githubusercontent.com/42539664/163391128-bdee1373-2abc-483d-8508-a1a7d4d3541f.png)
Do you mean, the space should not be needed? so `123a message here`?

**Comment by wrac4242** [comment]
Currently, the talking module requires a space, and that is why that message failed. It would have been `167:emoji:`

**Comment by MattTheCuber** [comment]
> Currently, the talking module requires a space, and that is why that message failed. It would have been `167:emoji:`

Oh, I thought emojis started with `<` then the id and name...

**Comment by djohts** [comment]
> > Currently, the talking module requires a space, and that is why that message failed. It would have been `167:emoji:`
> 
> Oh, I thought emojis started with `<` then the id and name...

custom emojis yes, default emojis are `:name:`

**Comment by wrac4242** [comment]
Also, don't forget to answer the question in the first message

**Comment by MattTheCuber** [comment]
> I am not entirely sure what you are asking, as the talking module does allow you to add messages after the count, separated by a space. ![image](https://user-images.githubusercontent.com/42539664/163391128-bdee1373-2abc-483d-8508-a1a7d4d3541f.png) Do you mean, the space should not be needed? so `123a message here`?

That is correct

**Comment by MattTheCuber** [comment]
> > > Currently, the talking module requires a space, and that is why that message failed. It would have been `167:emoji:`
> > 
> > 
> > Oh, I thought emojis started with `<` then the id and name...
> 
> custom emojis yes, default emojis are `:name:`

So it would work if you implemented my suggestion?

**Comment by wrac4242** [comment]
if it was implemented that way, it would work yes. Looking at the code, it would require an edit to this [line here](https://github.com/countr/countr/blob/e4a35b2843230818b9f20522f45640aa4aa5cf65/src/handlers/counting/index.ts#L36)

**Comment by wrac4242** [comment]
If promise is ok with it, ill probably implement it when I can

**Comment by MattTheCuber** [comment]
Awesome, would definitely help bc people are always saying bot broke when they do this lol

**Comment by promise** [comment]
i don't see a reason to generally allow something like `123hello` etc. but I can make an exception for emojis ig. For now, just tell your users to add a space instead

**Comment by wrac4242** [comment]
I will add now then
