### ISSUE TITLE
Editing message breaks countr

### ISSUE THREAD

**Issue by Oakchris1955** [countr/countr#239]
# Bug Report

Write a summary here. It can be as short as the short summary in the title, or longer.

## Reproducing

1. Run command '...'
2. Then count '...'
3. Then delete count '...'

## Expected behavior vs. Actual behavior

A clear description of what you expected to happen and what actually happened.

## Screenshots

If you have screenshots, please upload these.

**Comment by lacuna-exe** [comment]
This seems to be missing reproduction steps making it unclear _how_ it breaks , however this sounds like an issue that would be better suited for the support server.

**Comment by promise** [comment]
Seems like an issue that we can help you with in the support server like @e5510 said. Here's an invite: https://promise.solutions/support
