### ISSUE TITLE
[BOT] Support server link on top.gg

### ISSUE THREAD

**Issue by fabianneufang** [countr/countr#25]
# Bug

The invite link to the support server on top.gg and/or other platforms is/are invalid.

## Reproducing

1. Go to https://top.gg/bot/countr
2. Click "Join Support Server"

## Expected behavior

You should be able to join the server.

## Screenshots

https://cursed-images.xyz/i/5h01qcfb.png

**Comment by promise** [comment]
This is not a bug with the source code of Countr. Closing.
