### ISSUE TITLE
Expanded Timeout Role Functionality 

### ISSUE THREAD

**Issue by DiabolusGX** [countr/countr#254]
One of my friend reported an issue with webhook module not working properly when bot comes online after some time and missis some messages that leads to counter reset when someone counts wrong number.

### Example of above issue:
`ideasshared`'s msg was missed so they guessed `5` but I suppose according to bot, it was `4` since it was never captured and never post back by webhook.
![Resets when bot comes online](https://cdn.discordapp.com/attachments/802988374029238322/974019675098841128/IMG_5807.png)

### Suggestion:
Add a `penalty` module where you can set multiple thresholds and each threshold will have a penalty.
Example:
- 1 wrong count -> mute for 5 min.
- 5 wrong counts -> don't allow to count for 1 day.
- 10 wrong counts -> kick from server ...maybe??

I'm not sure how both things I said are relevant to each other but I got this idea when I head about the above problem so maybe using both these modules together we don't have to set "*counter being reset*" as a penalty on wrong count.

Also, I'd love to work on this new module if you'd like to have this in your bot.

**Comment by lacuna-exe** [comment]
This already somewhat exists under the timeout role feature (see https://docs.countr.xyz/#/commands?id=csettimeoutrole ) , although it doesn't quite have the scope of options you described.

**Comment by DiabolusGX** [comment]
> although it doesn't quite have the scope of options you described.

Yes, cuz it's limited to timeout role, basically adding a role for some time and what I'm talking about is completely different.
But it looks like you've made up your mind or you're not open for suggestions by changing title.

Also, pls look into the issue described before the feature request part.

**Comment by promise** [comment]
we're always open for suggestions (direct proof is that this suggestion is not closed), but this is indeed an expanded timeout role functionality as @e5510 said, which also fits the title better.

We're not planning on adding a module for this as modules are not that customizable, but we might however make something similar to the timeout functionality in our flows system.

**Comment by promise** [comment]
And please join our help server (<https://promise.solutions/support>) to get help with your issue above. We won't help with issues like these over GitHub.

**Comment by e5510** [comment]
In terms of the issue,we would be happy to help solve this in our support( https://promise.solutions/support ), however at a guess that server may not have the recover module enabled(You can check this by running c!modules and checking if there is a white dot next to recover.)

**Comment by DiabolusGX** [comment]
So If I'd like to set a penalty for 5 wrong counts in 1 min to be a kick from server, it's not possible right now but personally I think it doesn't sound like `Timeout Role Functionality` either, that's why I suggested a new module.
I don't have much in depth knowledge of bot's structure but if not module, maybe a penalty command? or renaming the `timeout role` command to something more generic such that timeout role is one of it's functionality not everything that command can do. (just UX point of view)
We can discuss further on this and would be happy to contribute if you'd like to add this to the bot.

**Comment by promise** [comment]
This sounds like a more advanced idea that we might do in the future, but doesn't seem like it has a high demand as of right now.

Closing but might reopen in the future.
