### ISSUE TITLE
[BOT] settimeoutrole Fails to use Markdown.

### ISSUE THREAD

**Issue by DuckMasterAl** [countr/countr#26]
# Typo

When you do `c!settimeoutrole` it says ":x: Invalid role. For help, type \`c!help timeoutrole"
Forgetting the end \`

## Screenshots
<img width="304" alt="Screen Shot 2020-05-06 at 7 59 47 PM" src="https://user-images.githubusercontent.com/43557963/81240037-54fe1d80-8fd4-11ea-9fca-db8722b183dd.png">

**Comment by fabianneufang** [comment]
See PR #27

**Comment by promise** [comment]
The issue will be fixed in the rewrite.
