### ISSUE TITLE
Errors I don't understand 

### ISSUE THREAD

**Issue by PokedWasTaken** [countr/countr#260]
573 verbose stack Error: ENOTEMPTY: directory not empty, rename '/home/container/node_modules/acorn-globals' -> '/home/container/node_modules/.acorn-globals-YxTwKFQv'
574 verbose cwd /home/container
575 verbose Linux 5.10.0-9-amd64
576 verbose node v17.9.0
577 verbose npm  v8.10.0
578 error code ENOTEMPTY
579 error syscall rename
580 error path /home/container/node_modules/acorn-globals
581 error dest /home/container/node_modules/.acorn-globals-YxTwKFQv
582 error errno -39
583 error ENOTEMPTY: directory not empty, rename '/home/container/node_modules/acorn-globals' -> '/home/container/node_modules/.acorn-globals-YxTwKFQv'
584 verbose exit -39
585 timing npm Completed in 1635ms
586 verbose unfinished npm timer reify 1653114882043
587 verbose unfinished npm timer reify:retireShallow 1653114883219
588 verbose code -39

**Comment by djohts** [comment]
~~try deleting `node_modules` and then doing `npm i` again?~~ nvm

May be deleting `node_modules` folder and `package-lock.json` file and then reinstalling `npm` would resolve your issue.

So, consider the following commands to apply the above operations:
```
rm -rf node_modules 
rm package-lock.json
npm install 
```

[src](https://stackoverflow.com/a/67992047/15145899)

**Comment by promise** [comment]
join the support server @ https://promise.solutions/discord and we'll help you out if we can
