### ISSUE TITLE
[BOT] Feature Request: Blocked Users

### ISSUE THREAD

**Issue by marens101** [countr/countr#28]
It would be nice to be able to block users from counting. I understand discord's native permissions could be used for this, but it would be nice to be able to use the bot instead so category permissions don't become unsynced.
Example use case: People that use alts to spam count. I'd like to block the alts but not their main accounts.

**Comment by Ta1al** [comment]
You could just make a new role and disable it's "SEND MESSAGES" permission from the category. That way the counting channel will still be in sync with the category channel and you can add that role to the user you want to block.

**Comment by fabianneufang** [comment]
You can just use the native permissions.
