### ISSUE TITLE
[BOT] *i cant off module allowspam*

### ISSUE THREAD

**Issue by meduzol94** [countr/countr#33]
# Bug

**You don't have in your bot command to off allowspam module? Because i kick your bot and reinvate it but it's still have allowspam module on**

## Reproducing

**1. Run command 'c!toggle allow-spam'**
**2. Run command 'c!toggle allow-spam'**

## Expected behavior

**I expected turning off module**

**Comment by fabianneufang** [comment]
Did you ensure that it said, that the module got turned off?

**Comment by meduzol94** [comment]
> Did you ensure that it said, that the module got turned off?

man i tried c!toggle allow-spam again and it dont off it

**Comment by promise** [comment]
Issues like this should be solved in our support server. https://promise.solutions/discord
