### ISSUE TITLE
[BOT] broken counting

### ISSUE THREAD

**Issue by Plakske-Kaas** [countr/countr#34]
# Bug

The channel doesn't work anymore. It keeps deleting everything number. On the top of the channel it says 'next count 203' but when we put that in it still doesn't work.

## Reproducing

1. Run command '...'
2. Then count '...'
3. Then delete count '...'

## Expected behavior

We were at 455 and multiple have already sent 456 but it keeps deleting it.

**Comment by fabianneufang** [comment]
Please send us a mesage in our support server: https://promise.solutions/discord
