### ISSUE TITLE
Add self-hosting instructions and general documentation

### ISSUE THREAD

**Issue by Ta1al** [countr/countr#379]
There is no `example.env` file to quickly edit config.
There's also no simple way of registering the slash commands.

**Comment by promise** [comment]
> There's also no simple way of registering the slash commands.

the interaction handler registers commands whenever shard 0's cluster is ready

**Comment by Ta1al** [comment]
So it sends a request every time the bot starts?

**Comment by promise** [comment]
yep. but it could be changed ig
