### ISSUE TITLE
Replies are ignored

### ISSUE THREAD

**Issue by MattTheCuber** [countr/countr#381]
# Bug Report

It seems that when someone replies to another message in the counting channel that the bot ignores it and does not increase the count. This confuses users as they see the previous reply message and assume they should count the next number even though the count was never increased making them fail.

## Reproducing

Counting example:
1. MattTheCuber: 50
2. AnotherPerson replying to MattTheCuber: 51 *gets ignored*
3. MattTheCuber: 52 *fails*

## Expected behavior vs. Actual behavior

I would expect that the bot should see the replied message and increase the count.

## Screenshots

![unknown-1](https://user-images.githubusercontent.com/32849887/184463427-9d5a4223-cf99-46b5-99bd-c02fa2ff5767.png)

**Comment by Ta1al** [comment]
I can confirm this bug exists.

**Comment by promise** [comment]
I've found a solution but I'm currently not home. will fix when I get home though

**Comment by promise** [comment]
resolved, not deployed to prod though. will slowly deploy it after some tests.
