### ISSUE TITLE
[DOCS] typo in social image

### ISSUE THREAD

**Issue by ajsirota** [countr/countr#39]
# Typo
The social image shows "couting" instead of "counting".

**Comment by fabianneufang** [comment]
We will have a look at it. Thank you for your help

**Comment by ajsirota** [comment]
Here's a screenshot 
![image](https://user-images.githubusercontent.com/67526318/93907131-d15a7a00-fcb1-11ea-9dd1-b2072afed77f.png)
**edit:** looks like the annotation didn't save. Anyway, it's in the second line of the copy.

**Comment by promise** [comment]
Solved it by just removing it, will make a better social image later.
