### ISSUE TITLE
Text alongside with the numbers Issue

### ISSUE THREAD

**Issue by Elemental2468** [countr/countr#407]
Hi, so the countr bot doesn't allow me to type in text along with the numbers next to it like
15 this is a example :D
This works in other servers but I am trying to help set it up for my friend but it doesn't seem to work. Can you help me?

Thanks!

**Comment by wrac4242** [comment]
Hi, have you enabled the module? run `/modules` then `read more about`, select `talking` then enable it there
also, next time go to the support server. reduces issues here

**Comment by Elemental2468** [comment]
Thank you! It works now!
Also thanks for letting me know to go to the support server instead of here.
