### ISSUE TITLE
Cannot list flows with too much content

### ISSUE THREAD

**Issue by kennethpdev** [countr/countr#48]
# Bug Report

I accidentally set a regex that is very long in one of my flows. Now when I list all the flows. It never return the embed content. It always says `An unknown error occurred. Do I have permission? (Embed Links)`. Perhaps the limit on the embed have been reached and its preventing to show the flows. Now there's no way for me to get the existing flows. Hoping we can list t hem without using the embed feature.

## Reproducing

1. create a flow with large content
2. then list using `c!listflows`
3. the error message will appear

## Expected behavior

The list of flows should appear

**Comment by Ta1al** [comment]
This is an actual issue that needs to be worked on and should not be closed just yet

**Comment by promise** [comment]
Fixed, will be live once the VPS gets back up.

**Comment by promise** [comment]
Still an issue for some people elsewhere when displaying flow content

**Comment by promise** [comment]
Should be fixed now 👍
