### ISSUE TITLE
Temporary Roles given in Flows

### ISSUE THREAD

**Issue by peter-leong** [countr/countr#51]
# Feature request

In the previous version of Countr, before flows were added, there were temporary roles that could be given once a specific trigger occurred. In my server what I would do is whoever counted a multiple of 25 would get a role called "current countr", and the next person who got the next multiple would "steal" the "current countr" role. If this could be added back that would be great.

**Comment by lacuna-exe** [comment]
This is still possible via the action’s in flows via the options one and three combined. `https://share.getcloudapp.com/12urnzyx`
