### ISSUE TITLE
The command c!setup doesnt work on my server

### ISSUE THREAD

**Issue by ElectroGaming55555** [countr/countr#62]
I am the owner of the server. I type c!setup, nothing. I type c!help. Oh, maybe I am doing this wrong, Let's try c!help setup! Oh! I have to type c!autosetup. Nothing. It doesn't work for some reason. I don't believe it is just that server, either.

**Comment by lacuna-exe** [comment]
Please join our support server linked above for help with this issue- nab. (Likely a permissions issue.)
