### ISSUE TITLE
flow editor doesn't work in some cases

### ISSUE THREAD

**Issue by promise** [countr/countr#641]
It's been an issue we've had since the beginning but we've never added an issue for it. Adding one now.

Basically, if the flow editor uses a flow (e.g. if it asks for any form of input) then it needs permission in the channel because of this wonky solution when using modals. https://github.com/countr/countr/blob/bbb0bcc87178d5b5130f108d8fd7113f7762c7cf/src/constants/editors/properties.ts#L99-L103

Explained: the flow editor responds with a modal to the original interaction, but when we get a modal back, we can't respond back by editing the original interaction. So we make a new one, and then delete the old one.

**Comment by ryanlua** [comment]
Issue is still occuring even today. I was stuck on creating a flow trigger in which selecting an input does nothing. Giving the bot administrator fixes the issue.
