### ISSUE TITLE
Add flow trigger where user has X score *or more*

### ISSUE THREAD

**Issue by Prozilla** [countr/countr#73]
Currently whenever a user gets a certain ampunt of points an action triggers but when you set this up after member's been counting and already passed that amount it won't trigger so it's be cool if it trigger whenever a member gained that amount of points OR more.

**Comment by promise** [comment]
@Prozilla I honestly can't seem to find a use case for this. Please explain why you would need this for your server.

**Comment by lacuna-exe** [comment]
Referencing where this was brought up [Message Link](https://discord.com/channels/449576301997588490/544222717373710356/807290343397130240) the use case it to give users who would've triggered the flow , but did so prior to the flow being implemented.

**Comment by promise** [comment]
Closing this as I honestly don't see a use case other than someone not getting their reward earlier.
