### ISSUE TITLE
Add an error message while attempting to add more triggers/actions than are available to the user.

### ISSUE THREAD

**Issue by lacuna-exe** [countr/countr#75]
# Feature request

Add an error message while attempting to add more triggers/actions than are available to the user, as it is not apparently clear as it doesn't prevent you from editing the second trigger and such, it just saves whatever trigger you added most recently .

[Image](https://open-this.questionable.link/QwkejG.png) - Second trigger shown in flow creation menu. (Not currently possible to have more than one trigger per flow on regular Countr.)

**Comment by promise** [comment]
• if the user wants to add more triggers/actions than what is allowed, it will send an error message
• if the user wants to edit triggers/actions past the limit then that is also possible
• when Countr checks for triggers and executes actions, it still only checks the first X triggers and executes only the first Y actions. See src/handlers/counting.js[#L119](https://github.com/countr/countr/blob/master/src/handlers/counting.js#L119) and [#L124](https://github.com/countr/countr/blob/master/src/handlers/counting.js#L124)

Closing this as it rarely happens and I also can't be bothered making more confusing code than what I can handle 😂
