### ISSUE TITLE
Counting in binary, hexadecimal, roman numerals and math equations

### ISSUE THREAD

**Issue by Mephistou** [countr/countr#77]
Counting channel, but just in roman numerals

**Comment by promise** [comment]
Not requested so much, will close this. If you want something like this, feel free to fork the source code and make it yourself :)

**Comment by Pearl8520** [comment]
Yes yes yes!

**Comment by wrac4242** [comment]
possibility of hexadecimal to be considered?

**Comment by promise** [comment]
> possibility of hexadecimal to be considered?

extending this issue

**Comment by lacuna-exe** [comment]
Any chance of skip counting qualifying under this?

**Comment by promise** [comment]
it is possible I guess, wouldn't be so hard. I don't really see a use case for it but sure

**Comment by promise** [comment]
Implemented 👍
