### ISSUE TITLE
Golden Hour

### ISSUE THREAD

**Issue by Lag2501** [countr/countr#772]
Hey! 

I'd like to suggest a Golden Hour for the count. Two ways to act on it: 

1. Make a way to turn on/off the BOT easily. It means that once it's ON again, it will understand the last count (if possible) and go on from that. Not the best option probably.

2. Keep it ON, but just trigger it so it won't reset the count or punish someone for one hour. During this hour, it keeps tracks of the count and delete mistakes on its own (99, 101, delete 101 to get back at 99). It could also remove or reduce the slowmode. After one hour, it sends a message to tell everyone that it's getting back (like a minute before). 

I prefer the second one as it allows the bot to keep working and follow the count with you, even helping you to deal with mistakes.

Hopefully you'll like the idea! ^.^

**Comment by promise** [comment]
I don't get what you mean here, Countr doesn't really "punish" anyone by default other than delete messages when they don't count correctly. If you have any flows or timeout roles then these can be manually disabled.

**Comment by Lag2501** [comment]
Yep. But I'm suggesting a way anyway :) Would love to have the "Golden hour", make it automatic so you don't have to do much and disable everything, then turn it on, setup count and all... Just an easy way for users with an auto moderation like example 2.

**Comment by promise** [comment]
Closing because I have no idea how I would ideally implement this and it seems far fetched from Countr's purpose at this point.
