### ISSUE TITLE
Add reload commands for troubleshooting etc.

### ISSUE THREAD

**Issue by promise** [countr/countr#79]
# Feature request

Add reload commands for troubleshooting etc. to reload commands and maybe even handlers. Also add support for it to reload across all shards.

**Comment by djohts** [comment]
In addition, maybe a shard respawn command?
Like: `c!respawn [0 | 0 1 2 | all]`

**Comment by promise** [comment]
> In addition, maybe a shard respawn command?
> Like: `c!respawn [0 | 0 1 2 | all]`

I can do this through eval instead if it's ever needed.
