### ISSUE TITLE
'shards': no such option in config

### ISSUE THREAD

**Issue by djohts** [countr/countr#80]
# *Bug* Report?

`config.shards` is requested in `sharding.js`, but there's no option `shards` in `config.json`

## Screenshots

![image](https://user-images.githubusercontent.com/68508885/110317722-36fab280-8015-11eb-969a-4b087de4b4b0.png)
![image](https://user-images.githubusercontent.com/68508885/110317797-4974ec00-8015-11eb-939e-0f5ca60a2798.png)

**Comment by promise** [comment]
Intended. When self-hosting, you really only need one shard.
