### ISSUE TITLE
Top counter has a role

### ISSUE THREAD

**Issue by promise** [countr/countr#94]
# Feature request

Create a way to add a flow and action to the top counter / score in a server. I’m attempting to have a role automatically assigned to the top counter, and removed from anyone else who was top counter before.

This would be great for competition within a server to maintain the highest count. And just easier on the admins for not having to add/remove a top role every day.

Suggested by Fuego#0003

**Comment by lacuna-exe** [comment]
Possibly building on this idea- what if instead of just highest score  it could be position in leaderboard (allow for first,second,and third roles)

**Comment by promise** [comment]
If I make a flow of this, I would have to calculate and store all user's ranking and then compare them each time someone counts. If someone has a more optimized way of doing it then feel free to send a message. Maybe it'll be restricted to the top three or top five people, that would be better.

**Comment by RuralAnemone** [comment]
you might be able to have it take scores from the liveboard, but the only downside to that would be that it wouldn't be fully live...

**Comment by wrac4242** [comment]
on update to the leaderboard event?

**Comment by RuralAnemone** [comment]
yes, that was what I was thinking

[edit: sorry I thought you meant liveboard :) ]

**Comment by wrac4242** [comment]
if it is directly linked to the leaderboard update, it should be as live as possible

**Comment by wrac4242** [comment]
then you only need to remove the role off the person in 2nd place if they have it and add it to 2nd place

**Comment by RuralAnemone** [comment]
good point
although I'm not sure how much that would affect latency and whatnot
you could use multiprocessing (or some equivalent of checking if the first place person has fewer points than the second place person (and the third, and the fourth, etc...), then using another script to change the roles around)
