### ISSUE TITLE
`c!reloadcommand` doesn't work with alias

### ISSUE THREAD

**Issue by djohts** [countr/countr#97]
# Bug Report

`c!reloadcommand` doesn't work well when command alias is provided. It says `Command has been reloaded successfully.` but at the same time throws an error in console.

## Reproducing

1. Try to reload a command by an alias, for example `c!reloadcommand !`

## Expected behavior

Basic command reload with no errors

## Screenshots

![image](https://user-images.githubusercontent.com/68508885/111900891-b2a92600-8a3d-11eb-8c84-b85acc0e6005.png)
![image](https://user-images.githubusercontent.com/68508885/111900906-c3599c00-8a3d-11eb-9275-b1188fd47ccf.png)

**Comment by promise** [comment]
Would be too much hassle also supporting aliases, it's based on the file system. Will keep this open, I can just make it so it checks if the file exists or not before doing it.

**Comment by djohts** [comment]
> Would be too much hassle also supporting aliases, it's based on the file system. Will keep this open, I can just make it so it checks if the file exists or not before doing it.

yeah, I meant more to check for the existence of a file than to support aliases

**Comment by fabianneufang** [comment]
> Would be too much hassle also supporting aliases, it's based on the file system. Will keep this open, I can just make it so it checks if the file exists or not before doing it.

Iirc you have the alias map that references to the file name. You could just get that name and then use the filename to reload it

**Comment by promise** [comment]
Reload command will not be implemented in the rewrite as the rewrite is in TypeScript through Docker, aka. I have to manually rebuild and restart a cluster for it to update a command.
